### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by nkdaiwan** [JXingZhao/EGNet#27]
The number of parameters: 111692618
Loading pre-trained model from ./epoch_vgg.pth...
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    main(config)
  File "run.py", line 21, in main
    test = Solver(None, test_loader, config, dataset.save_folder())
  File "/home/daiwan/PycharmProjects/EGNet-master/solver.py", line 52, in __init__
    self.net_bone.load_state_dict(torch.load(self.config.model))
  File "/home/daiwan/miniconda3/envs/env_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TUN_bone:
	Missing key(s) in state_dict: "convert.convert0.0.0.weight", "convert.convert0.1.0.weight", "convert.convert0.2.0.weight", "convert.convert0.3.0.weight", "convert.convert0.4.0.weight", "base.conv1.weight", "base.bn1.weight", "base.bn1.bias", "base.bn1.running_mean", "base.bn1.running_var", "base.layer1.0.conv1.weight", "base.layer1.0.bn1.weight", "base.layer1.0.bn1.bias", "base.layer1.0.bn1.running_mean", "base.layer1.0.bn1.running_var", "base.layer1.0.conv2.weight", "base.layer1.0.bn2.weight", "base.layer1.0.bn2.bias", "base.layer1.0.bn2.running_mean", "base.layer1.0.bn2.running_var", "base.layer1.0.conv3.weight", "base.layer1.0.bn3.weight", "base.layer1.0.bn3.bias", "base.layer1.0.bn3.running_mean", "base.layer1.0.bn3.running_var", "base.layer1.0.downsample.0.weight", "base.layer1.0.downsample.1.weight", "base.layer1.0.downsample.1.bias", "base.layer1.0.downsample.1.running_mean", "base.layer1.0.downsample.1.running_var", "base.layer1.1.conv1.weight", "base.layer1.1.bn1.weight", "base.layer1.1.bn1.bias", "base.layer1.1.bn1.running_mean", "base.layer1.1.bn1.running_var", "base.layer1.1.conv2.weight", "base.layer1.1.bn2.weight", "base.layer1.1.bn2.bias", "base.layer1.1.bn2.running_mean", "base.layer1.1.bn2.running_var", "base.layer1.1.conv3.weight", "base.layer1.1.bn3.weight", "base.layer1.1.bn3.bias", "base.layer1.1.bn3.running_mean", "base.layer1.1.bn3.running_var", "base.layer1.2.conv1.weight", "base.layer1.2.bn1.weight", "base.layer1.2.bn1.bias", "base.layer1.2.bn1.running_mean", "base.layer1.2.bn1.running_var", "base.layer1.2.conv2.weight", "base.layer1.2.bn2.weight", "base.layer1.2.bn2.bias", "base.layer1.2.bn2.running_mean", "base.layer1.2.bn2.running_var", "base.layer1.2.conv3.weight", "base.layer1.2.bn3.weight", "base.layer1.2.bn3.bias", "base.layer1.2.bn3.running_mean", "base.layer1.2.bn3.running_var", "base.layer2.0.conv1.weight", "base.layer2.0.bn1.weight", "base.layer2.0.bn1.bias", "base.layer2.0.bn1.running_mean", "base.layer2.0.bn1.running_var", "base.layer2.0.conv2.weight", "base.layer2.0.bn2.weight", "base.layer2.0.bn2.bias", "base.layer2.0.bn2.running_mean", "base.layer2.0.bn2.running_var", "base.layer2.0.conv3.weight", "base.layer2.0.bn3.weight", "base.layer2.0.bn3.bias", "base.layer2.0.bn3.running_mean", "base.layer2.0.bn3.running_var", "base.layer2.0.downsample.0.weight", "base.layer2.0.downsample.1.weight", "base.layer2.0.downsample.1.bias", "base.layer2.0.downsample.1.running_mean", "base.layer2.0.downsample.1.running_var", "base.layer2.1.conv1.weight", "base.layer2.1.bn1.weight", "base.layer2.1.bn1.bias", "base.layer2.1.bn1.running_mean", "base.layer2.1.bn1.running_var", "base.layer2.1.conv2.weight", "base.layer2.1.bn2.weight", "base.layer2.1.bn2.bias", "base.layer2.1.bn2.running_mean", "base.layer2.1.bn2.running_var", "base.layer2.1.conv3.weight", "base.layer2.1.bn3.weight", "base.layer2.1.bn3.bias", "base.layer2.1.bn3.running_mean", "base.layer2.1.bn3.running_var", "base.layer2.2.conv1.weight", "base.layer2.2.bn1.weight", "base.layer2.2.bn1.bias", "base.layer2.2.bn1.running_mean", "base.layer2.2.bn1.running_var", "base.layer2.2.conv2.weight", "base.layer2.2.bn2.weight", "base.layer2.2.bn2.bias", "base.layer2.2.bn2.running_mean", "base.layer2.2.bn2.running_var", "base.layer2.2.conv3.weight", "base.layer2.2.bn3.weight", "base.layer2.2.bn3.bias", "base.layer2.2.bn3.running_mean", "base.layer2.2.bn3.running_var", "base.layer2.3.conv1.weight", "base.layer2.3.bn1.weight", "base.layer2.3.bn1.bias", "base.layer2.3.bn1.running_mean", "base.layer2.3.bn1.running_var", "base.layer2.3.conv2.weight", "base.layer2.3.bn2.weight", "base.layer2.3.bn2.bias", "base.layer2.3.bn2.running_mean", "base.layer2.3.bn2.running_var", "base.layer2.3.conv3.weight", "base.layer2.3.bn3.weight", "base.layer2.3.bn3.bias", "base.layer2.3.bn3.running_mean", "base.layer2.3.bn3.running_var", "base.layer3.0.conv1.weight", "base.layer3.0.bn1.weight", "base.layer3.0.bn1.bias", "base.layer3.0.bn1.running_mean", "base.layer3.0.bn1.running_var", "base.layer3.0.conv2.weight", "base.layer3.0.bn2.weight", "base.layer3.0.bn2.bias", "base.layer3.0.bn2.running_mean", "base.layer3.0.bn2.running_var", "base.layer3.0.conv3.weight", "base.layer3.0.bn3.weight", "base.layer3.0.bn3.bias", "base.layer3.0.bn3.running_mean", "base.layer3.0.bn3.running_var", "base.layer3.0.downsample.0.weight", "base.layer3.0.downsample.1.weight", "base.layer3.0.downsample.1.bias", "base.layer3.0.downsample.1.running_mean", "base.layer3.0.downsample.1.running_var", "base.layer3.1.conv1.weight", "base.layer3.1.bn1.weight", "base.layer3.1.bn1.bias", "base.layer3.1.bn1.running_mean", "base.layer3.1.bn1.running_var", "base.layer3.1.conv2.weight", "base.layer3.1.bn2.weight", "base.layer3.1.bn2.bias", "base.layer3.1.bn2.running_mean", "base.layer3.1.bn2.running_var", "base.layer3.1.conv3.weight", "base.layer3.1.bn3.weight", "base.layer3.1.bn3.bias", "base.layer3.1.bn3.running_mean", "base.layer3.1.bn3.running_var", "base.layer3.2.conv1.weight", "base.layer3.2.bn1.weight", "base.layer3.2.bn1.bias", "base.layer3.2.bn1.running_mean", "base.layer3.2.bn1.running_var", "base.layer3.2.conv2.weight", "base.layer3.2.bn2.weight", "base.layer3.2.bn2.bias", "base.layer3.2.bn2.running_mean", "base.layer3.2.bn2.running_var", "base.layer3.2.conv3.weight", "base.layer3.2.bn3.weight", "base.layer3.2.bn3.bias", "base.layer3.2.bn3.running_mean", "base.layer3.2.bn3.running_var", "base.layer3.3.conv1.weight", "base.layer3.3.bn1.weight", "base.layer3.3.bn1.bias", "base.layer3.3.bn1.running_mean", "base.layer3.3.bn1.running_var", "base.layer3.3.conv2.weight", "base.layer3.3.bn2.weight", "base.layer3.3.bn2.bias", "base.layer3.3.bn2.running_mean", "base.layer3.3.bn2.running_var", "base.layer3.3.conv3.weight", "base.layer3.3.bn3.weight", "base.layer3.3.bn3.bias", "base.layer3.3.bn3.running_mean", "base.layer3.3.bn3.running_var", "base.layer3.4.conv1.weight", "base.layer3.4.bn1.weight", "base.layer3.4.bn1.bias", "base.layer3.4.bn1.running_mean", "base.layer3.4.bn1.running_var", "base.layer3.4.conv2.weight", "base.layer3.4.bn2.weight", "base.layer3.4.bn2.bias", "base.layer3.4.bn2.running_mean", "base.layer3.4.bn2.running_var", "base.layer3.4.conv3.weight", "base.layer3.4.bn3.weight", "base.layer3.4.bn3.bias", "base.layer3.4.bn3.running_mean", "base.layer3.4.bn3.running_var", "base.layer3.5.conv1.weight", "base.layer3.5.bn1.weight", "base.layer3.5.bn1.bias", "base.layer3.5.bn1.running_mean", "base.layer3.5.bn1.running_var", "base.layer3.5.conv2.weight", "base.layer3.5.bn2.weight", "base.layer3.5.bn2.bias", "base.layer3.5.bn2.running_mean", "base.layer3.5.bn2.running_var", "base.layer3.5.conv3.weight", "base.layer3.5.bn3.weight", "base.layer3.5.bn3.bias", "base.layer3.5.bn3.running_mean", "base.layer3.5.bn3.running_var", "base.layer4.0.conv1.weight", "base.layer4.0.bn1.weight", "base.layer4.0.bn1.bias", "base.layer4.0.bn1.running_mean", "base.layer4.0.bn1.running_var", "base.layer4.0.conv2.weight", "base.layer4.0.bn2.weight", "base.layer4.0.bn2.bias", "base.layer4.0.bn2.running_mean", "base.layer4.0.bn2.running_var", "base.layer4.0.conv3.weight", "base.layer4.0.bn3.weight", "base.layer4.0.bn3.bias", "base.layer4.0.bn3.running_mean", "base.layer4.0.bn3.running_var", "base.layer4.0.downsample.0.weight", "base.layer4.0.downsample.1.weight", "base.layer4.0.downsample.1.bias", "base.layer4.0.downsample.1.running_mean", "base.layer4.0.downsample.1.running_var", "base.layer4.1.conv1.weight", "base.layer4.1.bn1.weight", "base.layer4.1.bn1.bias", "base.layer4.1.bn1.running_mean", "base.layer4.1.bn1.running_var", "base.layer4.1.conv2.weight", "base.layer4.1.bn2.weight", "base.layer4.1.bn2.bias", "base.layer4.1.bn2.running_mean", "base.layer4.1.bn2.running_var", "base.layer4.1.conv3.weight", "base.layer4.1.bn3.weight", "base.layer4.1.bn3.bias", "base.layer4.1.bn3.running_mean", "base.layer4.1.bn3.running_var", "base.layer4.2.conv1.weight", "base.layer4.2.bn1.weight", "base.layer4.2.bn1.bias", "base.layer4.2.bn1.running_mean", "base.layer4.2.bn1.running_var", "base.layer4.2.conv2.weight", "base.layer4.2.bn2.weight", "base.layer4.2.bn2.bias", "base.layer4.2.bn2.running_mean", "base.layer4.2.bn2.running_var", "base.layer4.2.conv3.weight", "base.layer4.2.bn3.weight", "base.layer4.2.bn3.bias", "base.layer4.2.bn3.running_mean", "base.layer4.2.bn3.running_var". 
	Unexpected key(s) in state_dict: "base.base.0.weight", "base.base.0.bias", "base.base.2.weight", "base.base.2.bias", "base.base.5.weight", "base.base.5.bias", "base.base.7.weight", "base.base.7.bias", "base.base.10.weight", "base.base.10.bias", "base.base.12.weight", "base.base.12.bias", "base.base.14.weight", "base.base.14.bias", "base.base.17.weight", "base.base.17.bias", "base.base.19.weight", "base.base.19.bias", "base.base.21.weight", "base.base.21.bias", "base.base.24.weight", "base.base.24.bias", "base.base.26.weight", "base.base.26.bias", "base.base.28.weight", "base.base.28.bias", "base.base_ex.ex.0.weight", "base.base_ex.ex.2.weight", "base.base_ex.ex.4.weight".
您好，我运行了您的代码 ，出现了这样的错误，想向您请教一下我这个问题出在哪？希望您能回复我，谢谢！

**Comment by LIMENG0307** [comment]
我也是，请问你解决了吗？

**Comment by wuzht** [comment]
你把vgg模型加载到resnet上了吧
