### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by simantika** [JXingZhao/EGNet#30]
Traceback (most recent call last):
  File "run.py", line 71, in <module>
    main(config)
  File "run.py", line 17, in main
    train.train()
  File "/home/paramshavakmahesha/Documents/TRY4/EGNet/solver.py", line 154, in train
    sal_image, sal_label, sal_edge = sal_image.cuda(), sal_label.cuda(), sal_edge.cuda()
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by simantika** [comment]
How to remove this error? I used pytorch 1.0.0 version and torchvision 0.2.1
